chaos/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from flask_login import login_user, logout_user, current_user 
from werkzeug.security import check_password_hash

from chaos.extensions import db 
from chaos.models import User 
from datetime import datetime 
import pytz 

auth = Blueprint('auth', __name__)

def user_already_exists(email):
    users = User.query.all()
    for user in users:
        if user.email == email:
            return True 
    return False 

@auth.route('/admin_login', methods = ['GET','POST'])
def admin_login():
    admins = User.query.all()
    error = status = ''
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        admin = None 
        for x in admins:
            if x.email == email:
                admin = x 
                break
        
        if not admin or not check_password_hash(admin.password, password):
            error = 'Invalid credentials'
        elif admin.is_admin:
            flash('You were successfully logged in', "message")
            login_user(admin)
            if current_user.start_time == None:
                dt = datetime.now(tz=pytz.UTC)
                current_user.start_time = dt.astimezone(pytz.timezone('Asia/kolkata'))
                db.session.commit()
        else:
            error = 'you are not an admin'
        return render_template('admin_login.html', error = error)
    return render_template('admin_login.html', error=error)



@auth.route('/admin_olagebaa', methods = ['GET','POST'])
def admin_register():
    error = ''
    if request.method == 'POST':
        name = request.form['name']
        unhashed_passwd = request.form['password']
        unhashed_confirm_passwd = request.form['confirm_password']
        email = request.form['email']
        phone = request.form['phone']
        if unhashed_passwd != unhashed_passwd:
            error = 'passwords does not match'
        elif user_already_exists(email):
            error = 'user already exists'
        else:
            user = User(name=name, email=email, unhashed_password=unhashed_passwd, phone=phone, is_admin=True, attempts='', present_try=0, nextq=1, hint=-1, score=0)
            db.session.add(user)
            db.session.commit()
            flash("Registration Successful","message")
            return redirect(url_for('auth.admin_login'))

    return render_template('admin_register.html',error=error)


@auth.route('/olagebaa', methods=['GET','POST'])
def register():
    error = ''
    if request.method=='POST':
        name = request.form['name']
        unhashed_passwd = request.form['password']
        unhashed_confirm_passwd = request.form['confirm_password']
        email = request.form['email']
        phone = request.form['phone']
        if unhashed_passwd != unhashed_confirm_passwd:
            error = 'passwords does not match'
        elif user_already_exists(email):
            error = 'user already exists'
        else:
            user = User(name=name, email=email, unhashed_password=unhashed_passwd, phone=phone, is_admin=False, attempts='', present_try=0, nextq=1, hint=-1, score=0)
            db.session.add(user)
            db.session.commit()
            flash("Registration Successful", "message")
            return redirect(url_for('auth.login'))
    
    return render_template('register.html', error=error)

@auth.route('/login', methods=['GET','POST'])
def login():
    error = ''
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        user = User.query.filter_by(email=email).first()
        
        if not user or not check_password_hash(user.password, password):
            error = 'Invalid credentials'
        
        if not error:
            login_user(user)    
            flash("you are successfully logged in", "message")
            if current_user.start_time == None:
                dt = datetime.now(tz=pytz.UTC)           
                current_user.start_time = dt.astimezone(pytz.timezone('Asia/Kolkata'))
                db.session.commit()
            return redirect(url_for('main.instructions'))

    return render_template('login.html', error=error)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@auth.route('/admin_logout')
def admin_logout():
    logout_user()
    return redirect(url_for('main.home'))

chaos/routes/main.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, session
from flask_login import current_user, login_required, logout_user 

from chaos.extensions import db
from chaos.models import User 
from datetime import datetime 
import pytz
import os 
import requests 

main = Blueprint('main',__name__)

def get_cnt_n_hints_for(question_number):
    # write all hints and answers here

    hints = [
            [("Hint", "Read the Quote again"), 
            ("Hint", "Focus on words 'reverse' and 'language' "), 
            ("Hint", "Reverse the code word"), 
            ("Answer", "welcome (Explanation: Time cannot be reversed, who said language cannot be?!! the given  string is the reversed format of 'herzlich wilkommen' , welcome in German)")],

            [("Hint", "Google Googol"), 
            ("Hint", "log(100) = 2, 2 is the value that 10 must be raised to, to get 100"), 
            ("Hint", "modulo division gives the remainder after division (Example: 5 % 2 = 1)"), 
            ("Answer", "98 (Explanation: Googol is 1 followed by a hundred zeros. Google was founded in 1998. Modulo division is the remainder obtained after a division. Thus 1998 \% \log(Googol) = 98)")],


            [("Hint", "If I come to your house, it won't be a pleasant day for you"), 
            ("Hint", "An anagram is a word or phrase formed by rearranging the letters of a different word or phrase"), 
            ("Hint", "I'm so famous rather infamous now a days that I come on the news everywhere and everyday"), 
            ("Answer", "coronavirus (Explanation: 'coronavirus' is an anagram of 'carnivorous'. Seems trendy enough?)")],
            
            
            [("Hint", "Remember the language used in first question"), 
            ("Hint", "This city was divided into East and West till 1990"), 
            ("Hint", "A character in Money Heist"), 
            ("Answer", "Berlin (Explanation: JFK in his famous speech in Berlin Germany, infamously said 'Ich bin ein Berliner' which translates to 'I am a jelly dougnut', the city here refers to Berlin.)")],


            [("Hint", "Sometimes all you can do is write down what you see"), 
            ("Hint", "Yeah it is Morse code!"), 
            ("Hint", " Go to https://morsecode.world/international/translator.html"), 
            ("Answer", "enilsihtesrever (Explanation:  every dah is '-' and every dit is a '.' The given series is a morse code pattern that says 'reversethisline'. So you have to do just that!!)")],
            
            
            [("Hint", "It’s not arithmetic"), 
            ("Hint", "You know right, all places in the world can be virtualized, Search there to get the answer"), 
            ("Hint", "I symbolize love"), 
            ("Answer", "heart (Explanation: The above two numbers are the coordinates of the globe. Entering them in google maps will lead you to a 'heart'.)")],

            [("Hint", "Learn from the mistakes!!" ), 
            ("Hint", "There's a hidden message in the statement. Only one letter is wrong in each word."), 
            ("Hint", "Google the message and find guitar"), 
            ("Answer", "Smelly Cat (Explanation: After replacing the wrong letters with the correct ones, joining only the correct letters will result in 'Search for Phoebe'. Search in google and click on the guitar. A song sung by Phoebe pops up, which is named as Smelly Cat!)")],

            [("Hint", "Blacks and Whites represent the individual bits."), 
            ("Hint","The binary data needs to be inverted and converted!",), 
            ("Hint", "Remember, alphabets can also be represented in binary. Proceed from there."), 
            ("Answer","Stay Safe (Explanation: Using the clue Black is White and White is Black, we realise that we need to invert the bits. Converting it into ASCII results a link. In that link a mobile number is displayed and if you text your name to that number you will get the answer)")],

            [("Hint", "Some say everything humans know today can be found in this world"), 
            ("Hint", "Just use the link below; if you have missed it"), 
            ("Hint", "Its Greek letter that represents angular velocity"), 
            ("Answer", "omega (Explanation: Wikipedia logo is the world of puzzles! The only Greek alphabet on it is 'omega' !)")],

            [("Hint", "Some versions of it glow"), 
            ("Hint", "The key-word to decrypt is related to electronics"), 
            ("Hint", "focus on 'one way', 'rectify' and 'biased' in the riddle, don't forget to 'decode'"), 
            ("Answer", "Chaos is a ladder (Explanation: A simple diode(keyword) lets current flow in 'one way' that is when it is forward 'biased', this property is used in 'rectifiers' to convert 'oscillating' AC to DC)")],

            [("Hint", "Search a bit about the enigma machine. use '?' in the emulator to know more"), 
            ("Hint", "Make sure you make the proper connections!"), 
            ("Hint", "This is a secret society having an eye on a pyramid"), 
            ("Answer", "ILLUMINATI (Explanation: In the the enigma decryptor given, by setting the initial rotor positions as N I E, and connecting M-Y, S-O, R-E connections and typing KUANPVEMLX, would give 'illuminati')")],

            [("Hint", "Observe carefully"), 
            ("Hint", "Always try to 'know more' "), 
            ("Hint", "There are no errors in this game"), 
            ("Answer", "not available (Explanation: The point is to never give up! Click to know more page leads to another page where the answer is 'not available'. :P)")],

            [("Hint", "Browse this library according to the rules, don't forget the hex!"), 
            ("Hint", "If you have found a sentence, its actually a question"), 
            ("Hint", "Answer might surprise you, it's a number"), 
            ("Answer", "42 (Explanation: You should have figured out how to 'browse' the library, but the answer for that sentence is calculated by a supercomputer in 'The Hitchhiker's Guide to the Galaxy', and its 42. Interesting right.)")],

            [("Hint", "Expansion of pi: 3.141592653589793238462643383279502884197169"), 
            ("Hint", "The no. you are searching in pi lies between 500 - 700"), 
            ("Hint", "ISBN: International Standard Book Number, Usually found in the reference section"), 
            ("Answer", "05214-8455-3 (Explanation: The first 3 consecutive digits that's prime in PI are 653. Replacing x with 653 in the link, would lead to a page where a number is followed after ISBN '05214-8455-3'. That's the answer!!)")],

            [("Hint", "Read the riddle carefully and find out what the 'thing' is or rather its name"), 
            ("Hint", "If you have got the password, and found out the other clue, YOU should be able to solve this"), 
            ("Hint", "And its not the word 'you'! its you"), 
            ("Answer", "{} (Explanation: yeah its your username)".format(current_user.name))]
    
    ]

    return (14, hints[question_number - 1])

@main.route('/')
def home():
    return render_template('home.html')


@main.route('/instructions')
@login_required
def instructions():
    return render_template('inst.html', user=current_user)

@main.route('/disp_question')
@login_required
def disp_question():
    if current_user.nextq == 16:
        return redirect(url_for('main.treasure'))
    for i in range(1, 16):
        if current_user.nextq == i:
            return redirect(url_for('main.q' + str(i)))

@main.route('/illuminati')
def illuminati():
    return render_template('illuminati.html')


@main.route('/treasure')
@login_required
def treasure():
    return render_template('treasure.html')

@main.route('/finish')
@login_required
def finish():
    return render_template('finish.html')

@main.route('/OEYQ====', methods=['GET', 'POST'])
@login_required
def q1():
    if current_user.nextq != 1:
        return redirect(url_for('main.disp_question'))
    return render_template('q1.html')   

@main.route('/OEZA====', methods=['GET', 'POST'])
@login_required
def q2():
    if current_user.nextq != 2:
        return redirect(url_for('main.disp_question'))
    return render_template('q2.html') 


@main.route('/OEZQ====', methods=['GET', 'POST'])
@login_required
def q3():
    if current_user.nextq != 3:
        return redirect(url_for('main.disp_question'))
    return render_template('q3.html') 


@main.route('/MNXXE4TFMN2A====', methods=['GET', 'POST'])
@login_required
def correct():
    return render_template('correct.html')

@main.route('/OE2A====', methods=['GET', 'POST'])
@login_required
def q4():
    if current_user.nextq != 4:
        return redirect(url_for('main.disp_question'))
    return render_template('q4.html') 

@main.route('/OE2Q====', methods=['GET', 'POST'])
@login_required
def q5():
    if current_user.nextq != 5:
        return redirect(url_for('main.disp_question'))
    return render_template('q5.html') 

@main.route('/OE2B====', methods=['GET', 'POST'])
@login_required
def q6():
    if current_user.nextq != 6:
        return redirect(url_for('main.disp_question'))
    return render_template('q6.html')

@main.route('/OE2X====', methods=['GET', 'POST'])
@login_required
def q7():
    if current_user.nextq != 7:
        return redirect(url_for('main.disp_question'))
    return render_template('q7.html')

@main.route('/OE3X====', methods=['GET', 'POST'])
@login_required
def q8():
    if current_user.nextq != 8:
        return redirect(url_for('main.disp_question'))
    return render_template('q8.html')

@main.route('/OE4G====', methods=['GET', 'POST'])
@login_required
def q9():
    if current_user.nextq != 9:
        return redirect(url_for('main.disp_question'))
    return render_template('q9.html')

@main.route('/OE5C====', methods=['GET', 'POST'])
@login_required
def q10():
    if current_user.nextq != 10:
        return redirect(url_for('main.disp_question'))
    return render_template('q10.html')

chaos/templates/home.html
{% extends 'base.html' %}
{% block body %}
<br>
<div class="container">
<br><br><br>
<h1 style="font-size: 2.7rem; font-family: 'Eater', cursive;" class="ml-2 mr-2 text-responsive text-center display-4"> Constrained Chaos!!!!</h1>
<p style="font-family: 'Nova Script', cursive;" class="text-muted text-center">Genius Redifined</p><br>
<div class="text-center"><img style="opacity: 0.5;" width="200px" class="img-fluid" src="{{ url_for('static', filename='images/maze.jpg') }}" alt=""></div>
<br><br>
<!-- <p style="font-family: 'Nova Script', cursive;" class="text-center"><a href = "{{url_for('main.instructions')}}">Proceed to Instructions...</a></p> -->
{% if current_user.is_authenticated %}
<div class="text-center"><div class="text-center"><a class="my_btn" style="font-size: 1.8rem; font-family: 'Crimson Pro', serif;" href="{{ url_for('main.instructions') }}">Instructions</a></div></div>
{% else %}
<div class="text-center"><div class="text-center"><a class="my_btn" style="font-size: 1.8rem; font-family: 'Crimson Pro', serif;" href="{{ url_for('auth.login') }}">Login</a></div></div>
{% endif %}
</div>
<br>
{% if current_user.is_authenticated %}
<div class="text-center">
<a style="text-decoration: none; font-size: 15px;" href = "{{url_for('auth.logout')}}"><i class="fa fa-sign-out fa-2x" title="Logout" aria-hidden="true"></i></a>
</div>
{% endif %}
<br><br>
{% endblock %}

chaos/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <title>UCSP | Constrained Chaos</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Averia+Libre&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bitter&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static', filename='css/endgame.css')}}">

    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Berkshire+Swash&family=Crimson+Pro:wght@200&family=Inknut+Antiqua:wght@300&family=Kotta+One&family=PT+Serif+Caption&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Audiowide&family=Bigshot+One&family=Federant&family=Iceland&family=Nova+Oval&family=Nova+Square&family=Quantico&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Tulpen+One&display=swap" rel="stylesheet">    
    <link href="https://fonts.googleapis.com/css2?family=Merienda+One&display=swap" rel="stylesheet">    
    <style>
      body {
        min-height: 100vh;
        /* mobile viewport bug fix */
        min-height: -webkit-fill-available;
      }

      q,
      blockquote {
        quotes: "“" "”" "‘" "’";
        font-style: italic;
      }

      q:before,
      blockquote:before {
        content: open-quote;
      }

      q:after,
      blockquote:after {
        content: close-quote;
      }

      q:before,
      q:after,
      blockquote:before,
      blockquote:after {
        color: black;
        font-size: 1.2em;
      }

      blockquote {
        font-weight: bolder;
        margin-left: 0;
        padding-left: 1em;
      }



      body {
        outline: none;  
        background-color: whitesmoke;
      }
      
      .message {
        color: green;
      }

      .info {
        color: red;
      }

        #login_email, #login_pass {
        position: relative;
        margin: auto;
        width: 80%;
        background-color: inherit;
        border-top: none;
        border-left: none;
        border-right: none;
        border-bottom: 2px solid black;
        background-color: inherit;
        outline: 0px !important;
        -webkit-appearance: none !important;
        box-shadow: none !important;
      }

      input[name="Submit"] {
        color: black;
        text-decoration: none;
        padding: 6px 6px;
        padding-left: 15px;
        padding-right: 15px;
        border: 2px solid black;
      }

      input[name="Submit"]:hover {
        color: white;
        background-color: black;
      }

      #login_email:active, #login_email:focus {
        background-color: transparent;
        border-bottom: 2px solid black;
      }

      #login_pass:active, #login_pass:focus {
        background-color: transparent;
        border-bottom: 2px solid black;
      }

      .text-responsive {
        font-size: calc(90% + 0.5vw + 0.5vh);
      }
    </style>
</head>
<body> 
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
        <a id="ucsp" class="navbar-brand text-dark" href="/"><b style="font-family: 'Inknut Antiqua', serif">UCSP</b></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse w-100 order-3" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">            
           {% if current_user.is_authenticated %}
           <li class="nav-item">
            <a style="font-weight: bold; font-family: 'PT Serif Caption', serif !important;" class="mr-3 nav-link text-dark" href="{{ url_for('main.home') }}">Profile</a>
           </li>
            <li class="nav-item">    
              <a style="font-weight: bold; font-family: 'PT Serif Caption', serif !important;" class="mr-3 nav-link text-dark"  href="{{ url_for('auth.logout') }}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a style="font-weight: bold; font-family: 'PT Serif Caption', serif !important;" class="mr-3 nav-link text-dark" href="{{ url_for('main.home') }}">Home</a>
            </li>              
            <li class="nav-item">
                <a style="font-weight: bold; font-family: 'PT Serif Caption', serif !important;" class="mr-3 nav-link text-dark" href="{{ url_for('auth.login') }}">Log in</a>
              </li>
            {% endif %}
          </form>
        </div>
    </nav>
    <hr style="opacity: 0.3; border: 0.5px solid rgb(121, 116, 116); color: rgb(0, 0, 0); margin-top: 0;">
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <div class=flashes>
        {% for category, message in messages %}
          <p class="text-center mt-4 {{ category }}">{{ message }}</p>
        {% endfor %}
        </div>
      {% endif %}
    {% endwith %}
    {% block body %}
    {%endblock %}
  </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script type="text/javascript">  
  $(window).on('beforeunload', function()  
  {  
      $("input[type=submit], input[type=button]").prop("disabled", "disabled");  
  });  
</script>
</body>
</html>

chaos/templates/q1.html
  {% extends 'base.html' %}
{% block body %}

<br>
<div class="container">
    <div class="quest"><h2 class="text-secondary display-4 text-center">Quest <a class="" style="color: grey !important;" href="{{url_for('main.correct')}}" target="_blank">1</a>&nbsp;<a style="text-decoration: none; font-size: 15px; position: absolute; left: 88%; top: 4rem;" href = "{{url_for('auth.logout')}}"><i class="fa fa-sign-out fa-2x" title="Logout" aria-hidden="true"></i></a></h2></div>
    <hr style="height:1px;border-width:0;color:rgb(0, 195, 255);background-color:rgb(0, 195, 255)"><br>
    <blockquote class="text-center text-responsive m-auto lead">
        Time once lost cannot be reversed,
            <br>Unlike <u>Language</u>, which lives forever! </i> - Unknown 
      </blockquote><br>
      <h4><p style="font-size: 18px;" class="text-center lead">WELCOME to the brave and adventurous journey of a simple yet challenging Treasure Hunt...!!
        <br><br><p style="font-weight: 600;" class="text-center lead"><i> nemmoklliw hcilzreh </i></p> </h4> </p><br><br>
          <div class="text-center">
            {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %}
          {% for category, message in messages %}
          <p><i class="{{ category}}">{{message}}</i></p>
          {% endfor %} 
          {% endif %} {% endwith %}
       <div class="m-auto">
        <form class="form-group" action="{{ url_for('main.pro1') }}" method="POST" autocomplete="off">
          <span class="text-responsive">Enter your answer: </span>
          <input
            spellcheck="false"
            class="form_text ml-1 form-control"
            name="Answer"
            type="text"
            required
          /><br />
          <br /><br>
          <div class="text-responsive">
            <input
              class="btn"
              type="submit"
              name="Submit"
              value="Submit"
            />
          </div>
          </div>
        </form>
</div>
{% endblock %}

chaos/templates/q12.html
{% extends 'base.html' %}
{% block body %}

<br>
<div class="container">
    <h2 class="display-4 text-center text-secondary">Quest 12&nbsp;<a style="text-decoration: none; font-size: 15px; position: absolute; left: 88%; top: 4rem;" href = "{{url_for('auth.logout')}}"><i class="fa fa-sign-out fa-2x" title="Logout" aria-hidden="true"></i></a></h2>
    <hr style="height:1px;border-width:0;color:rgb(0, 195, 255);background-color:rgb(0, 195, 255)">

<br /><br /><br>

      <h3><p class="text-center text-muted"><a href="{{url_for('main.error1')}} " target="_blank">/treasurehuntv1.0</a></p></h3>

        <br><br><br><br>
        <div class="text-center">
          {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %}
        {% for category, message in messages %}
        <p><i class="{{ category}}">{{message}}</i></p>
        {% endfor %} 
        {% endif %} {% endwith %}
        
       <div class="m-auto">
        <form class="form-group" action="{{ url_for('main.pro12') }}" method="POST" autocomplete="off">
          <span class="text-responsive text-muted">Enter your answer: </span>
          <input
          spellcheck="false"
            class="form_text ml-1 form-control"
            name="Answer"
            type="text"
            required
          /><br />
          <br /><br>
          <div class="text-responsive">
            <input
              class="btn"
              type="submit"
              name="Submit"
              value="Submit"
            />
          </div>
        </div>
        </form>
</div>
{% endblock %}

chaos/templates/q14.html
{% extends 'base.html' %}
{% block body %}

<br>
<div class="container">
    <h2 class="display-4 text-center text-secondary">Quest 14&nbsp;<a style="text-decoration: none; font-size: 15px; position: absolute; left: 88%; top: 4rem;" href = "{{url_for('auth.logout')}}"><i class="fa fa-sign-out fa-2x" title="Logout" aria-hidden="true"></i></a></h2>
    <hr style="height:1px;border-width:0;color:rgb(0, 195, 255);background-color:rgb(0, 195, 255)"><br>
    <h5><p class="text-center text-muted">
      <i>en.wikipedia.org/wiki/x</i>
    </p></h5><br><br>

    <h4 class="text-center text-muted">x -> First 3 digit prime number in the consequtive digits in pi </h4><br><br><br><br>

    <h4 class="text-center text-muted">ISBN ____________ </h4>

        <br><br>
        <div class="text-center">
          {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %}
        {% for category, message in messages %}
        <p><i class="{{ category}}">{{message}}</i></p>
        {% endfor %} 
        {% endif %} {% endwith %}
       <div class="m-auto">
        <form class="form-group" action="{{ url_for('main.pro14') }}" method="POST" autocomplete="off">
          <span class="text-responsive text-muted">Enter your answer: </span>
          <input
          spellcheck="false"
            class="form_text ml-1 form-control"
            name="Answer"
            type="text"
            required
          /><br />
          <br /><br>
          <div class="text-responsive">
            <input
              
              class="btn"
              type="submit"
              name="Submit"
              value="Submit"
            />
          </div>
        </div>
        </form>
</div>
{% endblock %}

chaos/templates/q2.html
  {% extends 'base.html' %}
{% block body %}

<br>
<div class="container">
    <h2 class="display-4 text-center text-secondary">Quest 2&nbsp;<a style="text-decoration: none; font-size: 15px; position: absolute; left: 88%; top: 4rem;" href = "{{url_for('auth.logout')}}"><i class="fa fa-sign-out fa-2x" title="Logout" aria-hidden="true"></i></a></h2>
    <hr style="height:1px;border-width:0;color:rgb(0, 195, 255);background-color:rgb(0, 195, 255)">

      <br /><br /><br>

      <h5> <p class="text-center text-muted"> founded_year(Google) &nbsp; modulo-divided-by &nbsp; log(googol) =</p> </h5>

        <br><br><br><br>
        <div class="text-center">
          {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %}
        {% for category, message in messages %}
        <p><i class="{{ category}}">{{message}}</i></p>
        {% endfor %} 
        {% endif %} {% endwith %}
        
       <div class="m-auto">
        <form class="form-group" action="{{ url_for('main.pro2') }}" method="POST" autocomplete="off">
          <span class="text-responsive text-muted">Enter your answer: </span>
          <input
          spellcheck="false"
            class="form_text ml-1 form-control"
            name="Answer"
            type="text"
            required
          /><br />
          <br /><br>
          <div class="text-responsive">
            <input
              class="btn"
              type="submit"
              name="Submit"
              value="Submit"
            />
          </div>
        </div>
        </form><br><br><br><br><br><br><br>
        <p style="font-size: 13px;" class="text-right text-muted">Refer online sources for definitions.</p>
        
</div>
{% endblock %}